import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 text-white sticky top-0 z-50">
          <div className="container mx-auto">
            {/* Desktop & Mobile Scrollable Menu */}
            <div className="flex overflow-x-auto no-scrollbar whitespace-nowrap p-4 gap-6 items-center">
              <Link href="/" className="hover:text-blue-400 flex-shrink-0 font-bold">
                Home
              </Link>
              <div className="h-4 w-px bg-gray-600 flex-shrink-0" />
              <Link href="/price-tracker" className="text-blue-400 hover:text-blue-300 flex-shrink-0 font-bold">
                Price Tracker (PWA)
              </Link>
              <Link href="/three-good-things" className="text-orange-400 hover:text-orange-300 flex-shrink-0 font-bold">
                3 Good Things
              </Link>
              <Link href="/games/walkingfield" className="text-green-400 hover:text-green-300 flex-shrink-0 font-bold">
                WalkingField
              </Link>
              <Link href="/todo-pomodoro" className="hover:text-indigo-400 flex-shrink-0 font-bold">
                Todo & Pomodoro
              </Link>
              <Link href="/markdown-memo" className="hover:text-pink-400 flex-shrink-0 font-bold">
                Markdown Memo
              </Link>
              <Link href="/habit-tracker" className="hover:text-yellow-400 flex-shrink-0 font-bold">
                Habit Tracker
              </Link>
              <Link href="/todoapp" className="hover:text-gray-300 flex-shrink-0">
                TODO
              </Link>
              <Link href="/gambling" className="hover:text-gray-300 flex-shrink-0">
                Gambling
              </Link>
              <Link href="/games" className="hover:text-gray-300 flex-shrink-0">
                Games
              </Link>
              <Link href="/learning-nextjs" className="hover:text-gray-300 flex-shrink-0">
                Learning
              </Link>
              <Link href="/blog" className="hover:text-gray-300 flex-shrink-0">
                Blog
              </Link>
              <Link href="/image-organizer" className="hover:text-gray-300 flex-shrink-0">
                Images
              </Link>
            </div>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
